spring:
    #thymleaf
    thymeleaf:
      cache: false
#      content-type: text/html
#      mode: LEGACYHTML5

    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=Asia/Shanghai
      username: root
      password: root

      hikari:
        pool-name: DateHikariCP
        minimum-idle: 5
        idle-timeout: 1800000
        maximum-pool-size: 10
        auto-commit: true
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1

mybatis-plus:
  mapper-localtions: classpath*:/mapper/*Mapper.xml
  type-aliases-packge: com.xxx.seckill.pojo

logging:
  level:
    com.xxx.seckill.mapper: debug